WITH PRICE_INFO AS (
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
)

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT, PRICE_INFO
WHERE PRICE = PRICE_INFO.MAX_PRICE