WITH FISH AS (
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY 3